spring.thymeleaf.cache=false

server.port=8080

# Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Prometheus metrics endpoint
management.endpoint.prometheus.enabled=true

# Actuator base path
management.endpoints.web.base-path=/actuator
