name: App Deployment - Microk8s

on:
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: rootpromptnext/java-springboot-app

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create short commit SHA
        run: |
          git rev-parse --short HEAD > short_sha.txt

      - name: Docker Login (using GitHub Secrets)
        run: |
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USER }}" \
            --password-stdin

      - name: Build & Push Docker Image
        run: |
          SHORT_SHA=$(cat short_sha.txt)

          docker build -t java-springboot-app:$SHORT_SHA .
          docker tag java-springboot-app:$SHORT_SHA $IMAGE_NAME:$SHORT_SHA
          docker tag java-springboot-app:$SHORT_SHA $IMAGE_NAME:latest

          docker push $IMAGE_NAME:$SHORT_SHA
          docker push $IMAGE_NAME:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl get nodes
          kubectl apply -f deployment.yaml
